Blogpost for PyDelhi's Meetup held on June 9, 2018.
pydelhi/blog pull request #14
Opened 2018-06-23 19:05 UTC by im-gozmit

Please review.

2018-06-28 10:04 UTC, realslimshanky reviewed
Please squash your commits. Rest LGTM.

2018-06-29 00:23 UTC, dotgourav requested changes

2018-06-29 00:23 UTC, dotgourav commented on content/2018-06-09-pydelhi-meetup.md
> +It was a hot Saturday afternoon and still quite a lot tech enthusiasts and Python lovers gathered together at Fueled, Noida for the PyDelhi Meetup. The meetup, as usual, started with the quick and in
each person presents/gave(choose one)

2018-06-29 00:23 UTC, dotgourav commented on content/2018-06-09-pydelhi-meetup.md
> +Then we had a snacks break for half an hour where people got the chance to interact with each other, network and discuss more with each other. [Shashank Kumar](https://twitter.com/realslimshanky) and
Link PyCon India website here.

2018-07-12 20:52 UTC, im-gozmit commented
Thanks, @realslimshanky and @Gouravchawla for the edits.

2018-09-06 10:00 UTC, rajataaron commented
@realslimshanky can you please check the PR once and merge it.

2018-09-07 10:04 UTC, realslimshanky commented
@rajataaron I don't have merge access to this repo. @akshayaurora can you please help out here.

2018-09-07 11:58 UTC, akshayaurora commented
PR is not in mergeable state, please fix conflicts.

2018-09-07 12:00 UTC, akshayaurora commented on content/2018-06-09-pydelhi-meetup.md
> +<<<<<<< HEAD
conflicts ?

2018-09-09 18:47 UTC, realslimshanky commented
@im-gozmit please address reviews.

2019-03-04 12:00 UTC, aaqaishtyaq commented
Hey @im-gozmit, can you address requested changes.

2023-10-11 09:38 UTC, merged